# https://taskfile.dev

version: '3'

env:
  BUCKET: dateneimer
  AWS_REGION: eu-central-1

tasks:
  run:
    desc: Run benchmark
    deps: [build]
    cmds:
      - time ./fill.sh
    silent: false

  build:
    cmds:
      - go mod tidy
      - go build -o go-s3cp main.go
    silent: false

  init:
    cmds:
      - echo "No installation required"