# https://taskfile.dev

version: '3'

env:
  BUCKET: dateneimer

tasks:
  run:
    desc: Run benchmark
    cmds:
      - time ./fill.sh
    silent: false

  init:
    cmds:
      - echo "No installation required"