# https://taskfile.dev

version: '3'

env:
  BUCKET: dateneimer

tasks:
  run:
    desc: Run node
    cmds:
      - time node index.js

  init:
    cmds:
      - echo downloading libraries
      - npm i
