# https://taskfile.dev

version: '3'

env:
  BUCKET: dateneimer

tasks:
  run:
    desc: Run benchmark
    deps: [install]
    cmds:
      - time python3 app.py
    silent: false

  install:
    cmds:
      - pip3 install -r requirements.txt


