# https://taskfile.dev

version: '3'

env:
  BUCKET: dateneimer

tasks:
  run:
    desc: Run benchmark
    deps: [build]
    cmds:
      - time ./s3create100
    silent: false

  build:
    cmds:
      - go mod download
      - go build -o s3create100 main.go
    silent: false
