# https://taskfile.dev

version: '3'

env:
  BUCKET: dateneimer

tasks:
  init:
    desc: Install maven on cloud9
    cmds:
      - echo installing maven
      - cmd : |
          sudo wget http://repos.fedorapeople.org/repos/dchen/apache-maven/epel-apache-maven.repo -O /etc/yum.repos.d/epel-apache-maven.repo
          sudo sed -i s/\$releasever/6/g /etc/yum.repos.d/epel-apache-maven.repo
          sudo yum install -y apache-maven

  build:
    desc: build jar
    cmds:
      - mvn clean package
    silent: true

  run:
    desc: Run Java 
    deps: [build]
    cmds:
      - time mvn exec:java -Dexec.mainClass="hdi.S3Uploader"