# https://taskfile.dev

version: '3'

env:
  BUCKET: dateneimer

tasks:
  init:
    desc: Install maven on cloud9
    cmds:
      - Echo installing maven
      - sh -c "$(curl --location https://taskfile.dev/install.sh)" -- -d -b ~/.local/bin

  build:
    desc: build jar
    cmds:
      - mvn clean package
    silent: true

  run:
    desc: Run Java 
    deps: [build]
    cmds:
      - time mvn exec:java -Dexec.mainClass="hdi.S3Uploader"